/**
 * méthode qui renvoi un mot en le choisissant au hasard parmi une liste de mots
 *
 * si le niveau =3, le mot sera inférieur ou égal à 4 lettres
 *
 * @param int $niv  niveau de difficulté
 * @return  string  $mot    le mot choisi le dictionnaire
 *
 */
function choisirMot(niveau)
{
    dico = creerDico();

    
    if (niveau == 3) // mot <= à 4 lettres
    {
        do
        {
            nb = dico[Math.floor(Math.random() * dico.length)];
        } while ((nb.length) > 4);
        return nb;
    }
    else
    { //mot au hasard dans tout le dico
        return nb = dico[Math.floor(Math.random() * dico.length)];;
    }
}

/**
 * Affiche le tableau entré en paramètre
 * et sépare les lettres par des espaces.
 *
 * @param   array   tab    Tableau contentant une lettre par case.
 *
 * @return  void            Affiche le mot.
 */
function afficherTableau(tab)
{
    for (i = 0; i < tab.length; i++)
    {
        console.log(tab[i]);
    }
}

/**
 * méthode qui prend un mot en paramètre d'entrée et qui renvoi un tableau de caractères contenant autant de case que de lettres dans le mot.
 * si Niveau =1 les cases du milieu contiennent des _, les 1eres et dernières lettres restent apparantes
 * sinon Chacune de ces cases contient un _
 *
 * @param string mot
 * @param int niveau   //niveau de difficulté
 * @return void array
 */
function coderMot(mot, niveau)
{
    tab = mot.split('');
    if (niveau == 1)
    {
        for (i = 1; i < tab.length - 1; i++)
        {
            tab[i] = "_";
        }
    }
    else
    {
        for (i = 0; i < tab.length; i++)
        {
            tab[i] = "_";
        }
    }
    return tab;
}

function creerDico()
{
    //Cree le dictionnaire de mots
    var tabMots = ["AEROPORT",
    "AFFAIRE",
    "ALBUM",
    "ALPHABET",
    "AMENER",
    "AMPOULE",
    "ANCIEN",
    "ANORAK",
    "ANTENNE",
    "APPAREIL",
    "APPORTER",
    "APPUYER",
    "APRES",
    "ARC",
    "ARMOIRE",
    "ARRET",
    "ARRIERE",
    "ARRIVER",
    "ARROSER",
    "ASSIETTE",
    "ASSIS",
    "ATTACHER",
    "ATTENDRE",
    "ATTENTION",
    "ATTERRIR",
    "ATTRAPER",
    "AU",
    "AUTANT",
    "AUTO",
    "AUTOMOBILISTE",
    "AUTORADIO",
    "AUTOUR",
    "AVANCER",
    "AVANT",
    "AVEC",
    "AVION",
    "BAGAGE",
    "BAGUETTE",
    "BAIGNER",
    "BÂILLER",
    "BALLE",
    "BANC",
    "BARBE",
    "BARBOTER",
    "BARQUE",
    "BARRE",
    "BARREAU",
    "BAS",
    "BATEAU",
    "BEAUCOUP",
    "BIBLIOTHEQUE",
    "BLANC",
    "BLEU",
    "BOIS",
    "BOITE",
    "BONDIR",
    "BONNET",
    "BORD",
    "BOSSER",
    "BOTTE",
    "BOUCHER",
    "BOUCHON",
    "BOUDER",
    "BOUGER",
    "BOUSCULER",
    "BOUT",
    "BOUTEILLE",
    "BOUTON",
    "BRAS",
    "BRETELLE",
    "BRICOLAGE",
    "BRUIT",
    "BRUN",
    "BULLES",
    "BUREAU",
    "CABANE",
    "CABINET",
    "CAGOULE",
    "CAHIER",
    "CAISSE",
    "CALME",
    "CAMARADE",
    "CAMESCOPE",
    "CAMION",
    "CANARD",
    "CARNET",
    "CARREAU",
    "CARTABLE",
    "CARTON",
    "CASIER",
    "CASQUE",
    "CASQUETTE",
    "CASSE",
    "CASSER",
    "CASSEROLE",
    "CASSETTE",
    "CATALOGUE",
    "CEDE",
    "CEDEROM",
    "CEINTURE",
    "CERCEAU",
    "CHAINE",
    "CHAISE",
    "CHAISES",
    "CHANSON",
    "CHAPEAU",
    "CHARGER",
    "CHAT",
    "CHAUD",
    "CHAUSSETTE",
    "CHAUSSON",
    "CHAUSSURE",
    "CHEMISE",
    "CHERCHER",
    "CHEVILLE",
    "CHIFFRE",
    "CHOISIR",
    "CHOSE",
    "CHUCHOTER",
    "CHUTE",
    "CIGARETTE",
    "CINQ",
    "CISEAUX",
    "CLASSE",
    "CLAVIER",
    "CLE",
    "CLOU",
    "COIN",
    "COL",
    "COLERE",
    "COLLANT",
    "COLLE",
    "COLLER",
    "COLORIAGE",
    "COLORIER",
    "COMMENCER",
    "COMPARER",
    "COMPTER",
    "CONDUIRE",
    "CONSTRUIRE",
    "CONTE",
    "CONTINUER",
    "CONTRAIRE",
    "CONTRE",
    "COPAIN",
    "COPIER",
    "COQUILLAGE",
    "COQUILLETTE",
    "COQUIN",
    "CORDE",
    "CORPS",
    "COTE",
    "COU",
    "COUCHE",
    "COUDE",
    "COUDRE",
    "COULEUR",
    "COULOIR",
    "COUPER",
    "COURIR",
    "COURONNE",
    "COURT",
    "CRAIE",
    "CRAVATE",
    "CROCHET",
    "CROISSANT",
    "CUBE",
    "CUILLERE",
    "CUISSE",
    "CULOTTE",
    "CURIEUX",
    "CUVETTE",
    "DAME",
    "DANGER",
    "DANS",
    "DANSER",
    "DE",
    "DEBORDER",
    "DEBOUT",
    "DECHIRER",
    "DECOLLER",
    "DECORER",
    "DECOUPAGE",
    "DECOUPER",
    "DEDANS",
    "DEFENDRE",
    "DEHORS",
    "DELTAPLANE",
    "DEMANDER",
    "DEMARRER",
    "DEMOLIR",
    "DEPASSER",
    "DERNIER",
    "DERRIERE",
    "DESCENDRE",
    "DESOBEIR",
    "DESSIN",
    "DESSINER",
    "DETRUIRE",
    "DEUX",
    "DEUXIEME",
    "DEVANT",
    "DICTIONNAIRE",
    "DIFFERENCE",
    "DIFFERENT",
    "DIFFICILE",
    "DIRE",
    "DIRECTEUR",
    "DIRECTRICE",
    "DISCUTER",
    "DISPARAITRE",
    "DISTRIBUER",
    "DIX",
    "DOIGT",
    "DOIGTS",
    "DOMINO",
    "DONNER",
    "DORMIR",
    "DOS",
    "DOSSIER",
    "DOUCHE",
    "DOUCHER",
    "DOUX",
    "DROIT",
    "DU",
    "DUR",
    "EAU",
    "ECARTER",
    "ECHANGER",
    "ECHARPE",
    "ECHASSES",
    "ECHELLE",
    "ECLABOUSSER",
    "ECLAIRER",
    "ECOLE",
    "ECOUTER",
    "ECRAN",
    "ECRASER",
    "ECRIRE",
    "ECRITURE",
    "EFFACER",
    "EFFORT",
    "ELASTIQUE",
    "ELECTRICITE",
    "ELEVE",
    "EMMENER",
    "EMPORTER",
    "ENCORE",
    "ENERVE",
    "ENFANT",
    "ENFILER",
    "ENFONCER",
    "ENGIN",
    "ENLEVER",
    "ENTENDRE",
    "ENTONNOIR",
    "ENTOURER",
    "ENTREE",
    "ENTRER",
    "ENVELOPPE",
    "ENVOYER",
    "EPAIS",
    "EPAULE",
    "EPEE",
    "EQUIPE",
    "ESCABEAU",
    "ESCALADER",
    "ESCALIER",
    "ESCARGOT",
    "ESCARPIN",
    "ESSUYER",
    "ETAGERE",
    "ETANG",
    "ETIQUETTE",
    "ETROIT",
    "ETUDE",
    "ETUDIER",
    "EXPLIQUER",
    "EXTERIEUR",
    "FABRIQUER",
    "FACILE",
    "FAIRE",
    "FATIGUE",
    "FAUTE",
    "FAUTEUIL",
    "FEE",
    "FENETRE",
    "FERMER",
    "FESSE",
    "FEU",
    "FEUILLE",
    "FEUTRE",
    "FICELLE",
    "FIL",
    "FILET",
    "FILLE",
    "FILM",
    "FINIR",
    "FLECHE",
    "FLEUR",
    "FLOTTER",
    "FOIS",
    "FONCE",
    "FOND",
    "FOOTBALL",
    "FORT",
    "FOUILLER",
    "FRAPPER",
    "FREIN",
    "FROID",
    "FUSEE",
    "FUSIL",
    "GAGNER",
    "GANT",
    "GARAGE",
    "GARÇON",
    "GARDER",
    "GARDIEN",
    "GARE",
    "GAUCHE",
    "GENER",
    "GENOU",
    "GENTIL",
    "GLISSER",
    "GOLF",
    "GOMME",
    "GONFLER",
    "GOUTER",
    "GOUTTES",
    "GRAND",
    "GRIMPER",
    "GRIS",
    "GRONDER",
    "GROS",
    "GROUPE",
    "GRUE",
    "GYMNASTIQUE",
    "HABIT",
    "HANCHE",
    "HANDICAPE",
    "HAUT",
    "HELICOPTERE",
    "HEXAGONE",
    "HISTOIRE",
    "HORLOGE",
    "HUIT",
    "HUMIDE",
    "IDEE",
    "ILE",
    "IMAGE",
    "IMITER",
    "IMMEUBLE",
    "IMMOBILE",
    "INONDER",
    "INSEPARABLE",
    "INSTRUMENT",
    "INTERESSANT",
    "INTERIEUR",
    "INTRUS",
    "JALOUX",
    "JAMBES",
    "JAUNE",
    "JEAN",
    "JEU",
    "JOLI",
    "JOUER",
    "JOUET",
    "JUPE",
    "LAC",
    "LACER",
    "LACET",
    "LAINE",
    "LAISSER",
    "LARGE",
    "LAVABO",
    "LAVER",
    "LECTURE",
    "LETTRE",
    "LIERRE",
    "LIGNE",
    "LINGE",
    "LIRE",
    "LISSE",
    "LISTE",
    "LIT",
    "LITRE",
    "LIVRE",
    "LOIN",
    "LONG",
    "LUMIERE",
    "LUNETTES",
    "MADAME",
    "MAGAZINE",
    "MAGICIEN",
    "MAGIE",
    "MAGNETOSCOPE",
    "MAILLOT",
    "MAIN",
    "MAINS",
    "MAISON",
    "MAITRE",
    "MAITRESSE",
    "MAL",
    "MALADROIT",
    "MANCHE",
    "MANQUER",
    "MANTEAU",
    "MARCHE",
    "MARIONNETTE",
    "MARTEAU",
    "MATELAS",
    "MATERNELLE",
    "MELANGER",
    "MEME",
    "MENSONGE",
    "MESURER",
    "METAL",
    "METRE",
    "METTRE",
    "MEUBLE",
    "MICRO",
    "MIEUX",
    "MILIEU",
    "MINE",
    "MODELE",
    "MOINS",
    "MONTAGNE",
    "MONTER",
    "MONTRER",
    "MORCEAU",
    "MOT",
    "MOTEUR",
    "MOTO",
    "MOUCHOIR",
    "MOUFLE",
    "MOUILLE",
    "MOUILLER",
    "MOULIN",
    "MOUSSE",
    "MOYEN",
    "MUET",
    "MULTICOLORE",
    "MUR",
    "MUSCLE",
    "MUSIQUE",
    "NAGER",
    "NENUPHAR",
    "NEUF",
    "NŒUD",
    "NOIR",
    "NOM",
    "NOMBRE",
    "NOUVEAU",
    "NU",
    "NUMERO",
    "OBEIR",
    "OBJET",
    "OBLIGER",
    "ONGLE",
    "ORCHESTRE",
    "ORDINATEUR",
    "ORDRE",
    "OURS",
    "OUTIL",
    "OUVRIR",
    "PAGE",
    "PAIRE",
    "PANNE",
    "PANTALON",
    "PAPIER",
    "PARACHUTE",
    "PARCOURS",
    "PAREIL",
    "PARKING",
    "PARLER",
    "PARTAGER",
    "PARTIR",
    "PAS",
    "PASSERELLE",
    "PATAUGER",
    "PEDALO",
    "PEINDRE",
    "PEINTURE",
    "PELUCHE",
    "PENTE",
    "PERCER",
    "PERDRE",
    "PERLE",
    "PERSONNE",
    "PETIT",
    "PEU",
    "PEUR",
    "PHOTO",
    "PIED",
    "PIEDS",
    "PILOTE",
    "PINCEAU",
    "PION",
    "PLACARD",
    "PLAFOND",
    "PLAGE",
    "PLANCHE",
    "PLÂTRE",
    "PLEUVOIR",
    "PLI",
    "PLIAGE",
    "PLIER",
    "PLONGEOIR",
    "PLONGER",
    "PLUIE",
    "PLUS",
    "PNEU",
    "POCHE",
    "POIGNET",
    "POING",
    "POINT",
    "POINTE",
    "POINTU",
    "POISSON",
    "POLI",
    "POMPIERS",
    "PONT",
    "PORTE",
    "PORTEMANTEAU",
    "PORTER",
    "POSER",
    "POSTER",
    "POT",
    "POUBELLE",
    "POUCE",
    "POUSSER",
    "POUVOIR",
    "PREMIER",
    "PRENDRE",
    "PRENOM",
    "PREPARER",
    "PRES",
    "PRESENT",
    "PRESQUE",
    "PRESSER",
    "PRETER",
    "PRINCE",
    "PRISES",
    "PRIVER",
    "PROMETTRE",
    "PROPRE",
    "PUNAISE",
    "PUNIR",
    "PUZZLE",
    "PYJAMA",
    "PYRAMIDE",
    "QUAI",
    "QUATRE",
    "QUESTION",
    "RACONTER",
    "RADIATEUR",
    "RADIO",
    "RAME",
    "RAMPE",
    "RAMPER",
    "RANGER",
    "RATER",
    "RAYURE",
    "RECEVOIR",
    "RECITER",
    "RECOMMENCER",
    "RECREATION",
    "RECULER",
    "REFUSER",
    "REGARDER",
    "REINE",
    "REMETTRE",
    "REMPLACER",
    "REMPLIR",
    "RENTREE",
    "RENTRER",
    "RENVERSER",
    "REPARER",
    "REPETER",
    "REPONDRE",
    "RESPIRER",
    "RESSEMBLER",
    "RESTER",
    "RETARD",
    "REUSSIR",
    "REVENIR",
    "RIDEAU",
    "ROBE",
    "ROBINET",
    "ROI",
    "ROND",
    "ROUE",
    "ROUGE",
    "ROULADE",
    "ROULER",
    "ROUX",
    "RUBAN",
    "RUGUEUX",
    "SAGE",
    "SALADIER",
    "SALE",
    "SALLE",
    "SAUT",
    "SAUTER",
    "SAVON",
    "SCIE",
    "SEAU",
    "SEC",
    "SECHER",
    "SEMELLE",
    "SENS",
    "SENTIR",
    "SEPARER",
    "SEPT",
    "SERIEUX",
    "SERPENT",
    "SERRE",
    "SERRER",
    "SERRURE",
    "SERVIETTE",
    "SERVIR",
    "SEUL",
    "SIEGE",
    "SIESTE",
    "SILENCE",
    "SIX",
    "SOL",
    "SOLDAT",
    "SOLIDE",
    "SOMMEIL",
    "SONNER",
    "SONNETTE",
    "SORCIERE",
    "SORTIE",
    "SORTIR",
    "SOUFFLER",
    "SOULEVER",
    "SOULIGNER",
    "SOUPLE",
    "SOURD",
    "SOURIRE",
    "SOUS",
    "SPAGHETTI",
    "SPORT",
    "STYLO",
    "SUIVANT",
    "SUIVRE",
    "SUR",
    "SURFEUR",
    "TABLE",
    "TABLEAU",
    "TABLIER",
    "TABOURET",
    "TACHE",
    "TAILLE",
    "TAILLER",
    "TALON",
    "TAMBOUR",
    "TAMPON",
    "TAPER",
    "TAPIS",
    "TARD",
    "TASSE",
    "TELECOMMANDE",
    "TELEPHONE",
    "TELEVISION",
    "TENDRE",
    "TENIR",
    "TENNIS",
    "TERMINER",
    "TETE",
    "TIRER",
    "TIROIR",
    "TISSU",
    "TITRE",
    "TOBOGGAN",
    "TOILETTE",
    "TOMBER",
    "TORDU",
    "TOT",
    "TOUCHER",
    "TOUR",
    "TOURNER",
    "TOURNEVIS",
    "TRAIN",
    "TRAIT",
    "TRAMPOLINE",
    "TRANQUILLE",
    "TRANSPARENT",
    "TRANSPIRER",
    "TRANSPORTER",
    "TRAVAIL",
    "TRAVAILLER",
    "TRAVERSER",
    "TREMPER",
    "TRICHER",
    "TRICOT",
    "TRIER",
    "TROIS",
    "TROISIEME",
    "TROMPETTE",
    "TROP",
    "TROUER",
    "TROUS",
    "TROUSSE",
    "TUNNEL",
    "UN",
    "UNIFORME",
    "USE",
    "VACHE",
    "VALISE",
    "VASE",
    "VEHICULE",
    "VENIR",
    "VENTRE",
    "VERRE",
    "VERS",
    "VERSER",
    "VERT",
    "VESTE",
    "VETEMENT",
    "VIDER",
    "VIRAGE",
    "VIS",
    "VITE",
    "VITESSE",
    "VITRE",
    "VOITURE",
    "VOIX",
    "VOLER",
    "VOULOIR",
    "VOYAGE",
    "WAGON",
    "XYLOPHONE",
    "ZERO",
    "ZIGZAG"]

    return tabMots;
}

 function testerLettre(lettre, tab, depart)
 {
    tabRec = array_slice(tab, depart); // on détermine le tableau de recherche en fonction de la position depart.
     //Array_slice, permet d'extraire le sous tableau en fonction de la position
    // exemple array_slice(['B','O','N','J','O','U','R'], 5) donne ['U','R']
    res = array_search(lettre, tabRec); //recherche la lettre dans le tableau
    if (res === false) // === false pour eviter la confusion entre 0 et false
    {
        return [];
   }
     else
    {
         reponse[] = res + depart;
      tabPos = array_merge(reponse, testerLettre(lettre, tab, res + depart + 1)); // array_merge permet de fusionner le tableau résultat avec le tableau de l'appel recursif
        array_merge de [1,2] et [4] donne [1,2,4]
       return tabPos;
    }
 }

/**
 * méthode qui modifie le tableau passé en paramètre en affectant la lettre à la position passée en paramètre
 *
 * @param char lettre    lettre à placer
 * @param array tab       tableau dans lequel mettre la lettre
 * @param int pos       position à laquelle mettre la lettre
 * @return void             le tableau est mis à jour
 */
function ajouterUneLettre(lettre, tab, pos)
{
    tab[pos] = lettre;
    return tab;
}

function ajouterLesLettres(val, tab, tabpos, niveau)
{
    switch (niveau)
    {
        case 1:
            for (i = 0; i < tabpos.length; i++) //boucle permettant de parcourir le tableau des positions
                {
                tab = ajouterUneLettre(val, tab, tabpos[i]);
            }
            return tab;
        case 2:
        case 4:
            //on place les lettres une à une de gauche à droite
            for (i = 0; i < tabpos.length; i++) //on parcours les positions
                {
                posEtudiee = tabpos[i];
                //on verifie que la position n'est pas occupée
                if (tab[posEtudiee] != val)
                {
                    tab = ajouterUneLettre(val, tab, posEtudiee);
                    return tab;
                }
            }
            return -1; // plus de place pour la lettre
        case 3:
            // on place les lettres aléatoirement
            test=testerLettre(val,tab,0);    //on cherche les lettres déjà placées dans le mot code
            pos=array_diff(tabpos,test);     //différence entre les tableaux
            if(pos != '_')        //s'il reste des lettres à placer
            {
                posetudie = tabpos[Math.floor(Math.random() * tabpos.length)]
                tab = ajouterUneLettre(val, tab, posetudie);
                return tab;
            }
            else    //il n'y a plus de lettre à placer
            {
                return -1;
            }
    }
    return -1;
}


var niveau = 1;
//var mot = choisirMot(niveau);
var mot = 'toto';
console.log(mot);
var motC = coderMot(mot, niveau);

ajouterUneLettre('o', motC, 1);

afficherTableau(motC)
